# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=40)),
                ('movieTitle', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=150)),
                ('caption', models.TextField()),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
