# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181021_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='realated',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
